### ISSUE TITLE
Is there pretrained model?

### ISSUE THREAD

**Issue by leiwen83** [ARM-software/sesr#1]
Hi,

Could the pretrained model be downloaded for reference?

Thx,
Lei

**Comment by robell** [comment]
hi Lei, we recently published this: https://github.com/ARM-software/ML-zoo/tree/master/models/superresolution/SESR/tflite_int8

**Comment by leiwen83** [comment]
I check that download link, and found it is tflite version. Is there onnx version could be download?

**Comment by kbhardwa** [comment]
Hi Lei, we currently do not have an onnx version of this model. I will update this issue in case we release any such model but it is not currently planned. Thanks.
