### ISSUE TITLE
which method do you use to predict the hr_image

### ISSUE THREAD

**Issue by wyfzka** [ARM-software/sesr#12]
Could you tell me which method do you use ti predict the hr_image? I use `model.predict(lr_image)` to predict, but I got the result that it takes 0.18s per image(x2 to 720p) on my GPU(3060)
Thanks

**Comment by kbhardwa** [comment]
Hi. To do the inference, we first read the input low-resolution image file and convert it into Y-channel only using the functions inside utils.py (there is a [rgb_to_y function](https://github.com/ARM-software/sesr/blob/4813fa1e9ece28cea5abc6f55c6738da7c97cd02/utils.py#L51) ). Once the file is in the desired format, we just do the following to perform the inference (so we did not use ```model.predict(lr_image)```):
```
#Compute the upscaled image for a trained model
model = tf.saved_model.load(model_path)
model_out = model(y_lr)
```
Here, y_lr is input low-res image in y-channel format. model_path is the directory path that contains saved_model.pb file. I am not sure what difference you would see between model.predict and our inference pipeline latencies. Make sure you are doing inference on collapsed model only. As far as GPU latency is concerned, we deployed 360p-to-720p SR on a GPU on a real mobile device and got 20.38ms (see [Section 5.9 and Table 6 in our latest version here](https://arxiv.org/pdf/2103.09404.pdf)). For a large GPU, 0.18s certainly does not sound correct and I am not sure what could be wrong. Please update this issue if you find anything.

**Comment by wyfzka** [comment]
Sorry to bother you again. I met a bug when I use your code.
`
Traceback (most recent call last):
  File "/home/wyf/sesr/test2.py", line 45, in <module>
    model_out = model(IMAGE_y)
  File "/home/wyf/anaconda3/envs/sesr_tf/lib/python3.9/site-packages/tensorflow/python/saved_model/load.py", line 668, in _call_attribute
    return instance.__call__(*args, **kwargs)
  File "/home/wyf/anaconda3/envs/sesr_tf/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/home/wyf/anaconda3/envs/sesr_tf/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 894, in _call
    return self._concrete_stateful_fn._call_flat(
  File "/home/wyf/anaconda3/envs/sesr_tf/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/wyf/anaconda3/envs/sesr_tf/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 555, in call
    outputs = execute.execute(
  File "/home/wyf/anaconda3/envs/sesr_tf/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  assertion failed: [Trying to access a placeholder that is not supposed to be executed. This means you are executing a graph generated from the cross-replica context in an in-replica context.]
         [[node Assert/Assert (defined at /sesr/test2.py:45) ]] [Op:__inference_restored_function_body_5879]

Function call stack:
restored_function_body
`

I train and test model both on tf 2.4.1. I donnot konw what raise the error. This is my code.
`mirrored_strategy = tf.distribute.MirroredStrategy(devices=["/gpu:2"])
    with mirrored_strategy.scope():

        # RGB to Y
        IMAGE = imageio.imread('./42049_bicubic.png', pilmode="RGB")
        IMAGE = tf.convert_to_tensor(IMAGE)
        IMAGE = tf.cast(IMAGE, dtype=tf.float32)
        IMAGE_y = rgb_to_ycbcr(IMAGE)[... , 0:1]/255
        IMAGE_y = tf.reshape(IMAGE_y, shape=(1, IMAGE_y.shape[0], IMAGE_y.shape[1], 1))
        
        model = tf.saved_model.load(model_dir)
        model_out = model(IMAGE_y)

`
Hope to your reply! Thank you very much!

**Comment by kbhardwa** [comment]
Hi! I will try your code and update as soon as possible. Please allow me a week.

**Comment by wyfzka** [comment]
Thanks! You are so considerate!
Here is my complete code:
`
mirrored_strategy = tf.distribute.MirroredStrategy(devices=["/gpu:2"])
    with mirrored_strategy.scope():

        # RGB to Y
        IMAGE = imageio.imread('./42049_bicubic.png', pilmode="RGB")
        IMAGE = tf.convert_to_tensor(IMAGE)
        IMAGE = tf.cast(IMAGE, dtype=tf.float32)
        IMAGE_y = rgb_to_ycbcr(IMAGE)[... , 0:1]/255
        IMAGE_y = tf.reshape(IMAGE_y, shape=(1, IMAGE_y.shape[0], IMAGE_y.shape[1], 1))
        
        model = tf.saved_model.load(model_dir)
        model_out = model(IMAGE_y)
`
Thank you again~
