### ISSUE TITLE
Is there a pytorch version?

### ISSUE THREAD

**Issue by Vieeo** [ARM-software/sesr#2]

**Comment by kbhardwa** [comment]
Hi Vieeo, currently we do not have a pytorch version of this code. I will update this issue if we release any pytorch code on SESR but it is not currently planned. Thanks.

PS: If you just follow the SESR/Linear Block class code and adapt it to pytorch, it should be simple enough to train this model there.

**Comment by Solight96** [comment]
Do you still have no plans to release a pytorch version?

**Comment by Solight96** [comment]
Do you still have no plans to release a pytorch version?
