### ISSUE TITLE
how to load local dataset DIV2K?

### ISSUE THREAD

**Issue by fangichao** [ARM-software/sesr#6]
hi, how to load local dataset DIV2K? 
and how to orgnize the DIV2k directory?
THKs alot

**Comment by mrgreen3325** [comment]
Hello, I have the same problem.
May I know how u solve that?
Thanks.

**Comment by mrgreen3325** [comment]
> Hello, I have the same problem. May I know how u solve that? Thanks.

Hello, I have the same problem.
May I know how u solve that?
Thanks.
