### ISSUE TITLE
can use other dataset with lr-hr pair to train?

### ISSUE THREAD

**Issue by mrgreen3325** [ARM-software/sesr#8]
Thanks for your work.
I have a dataset with lr hr directory.
How to use this dataset to feed into the program to train?
Thanks.

**Comment by kbhardwa** [comment]
Hi. Sorry for the delay. We were working to release a new version of the paper which is now released on arXiv. For your question, the discussion [here](https://stackoverflow.com/questions/37340129/tensorflow-training-on-my-own-image) should be helpful to train the model with your own custom data.
